import 'dart:io';

import 'v3_color_token.dart';
import 'v3_token_parser.dart';
import 'v3_token_resolver.dart';

final class V3GenerationResult {
  const V3GenerationResult({
    required this.primitiveCount,
    required this.lightCount,
    required this.darkCount,
    required this.changedFiles,
  });

  final int primitiveCount;
  final int lightCount;
  final int darkCount;
  final int changedFiles;
}

final class V3ThemeGenerator {
  const V3ThemeGenerator({required this.repoRoot});

  final Directory repoRoot;

  V3GenerationResult generate() {
    final themeRoot = Directory('${repoRoot.path}/lib/config/themes/v3');
    final parser = const V3TokenParser();
    final resolver = const V3TokenResolver();
    final primitives = parser.parseFile(
      File('${themeRoot.path}/tokens/primitive.tokens.json'),
    );
    final light = parser.parseFile(
      File('${themeRoot.path}/tokens/semantic/light.tokens.json'),
    );
    final dark = parser.parseFile(
      File('${themeRoot.path}/tokens/semantic/dark.tokens.json'),
    );
    resolver.validateModeParity(light, dark);
    final resolvedLight = resolver.resolve(
      primitives: primitives,
      semantics: light,
    );
    final resolvedDark = resolver.resolve(
      primitives: primitives,
      semantics: dark,
    );

    final generatedDir = Directory('${themeRoot.path}/generated')
      ..createSync(recursive: true);
    var changed = 0;
    changed += _writeIfChanged(
      File('${generatedDir.path}/v3_primitive_colors.g.dart'),
      buildPrimitiveSource(primitives),
    );
    changed += _writeIfChanged(
      File('${generatedDir.path}/v3_semantic_colors.g.dart'),
      buildSemanticSource(resolvedLight, resolvedDark),
    );
    return V3GenerationResult(
      primitiveCount: primitives.length,
      lightCount: light.length,
      darkCount: dark.length,
      changedFiles: changed,
    );
  }

  String buildPrimitiveSource(List<V3ColorToken> primitives) {
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
      ..writeln('// Generated by v3_theme_generator.dart from tokens/**.')
      ..writeln()
      ..writeln("import 'package:flutter/material.dart';")
      ..writeln()
      ..writeln('abstract final class V3PrimitiveColors {');
    for (final token in primitives) {
      if (token.isAlias) continue;
      buffer.writeln(
        '  static const ${token.dartProperty} = Color(${_colorLiteral(token)});',
      );
    }
    buffer.writeln('}');
    return buffer.toString();
  }

  String buildSemanticSource(
    List<V3ResolvedColorToken> light,
    List<V3ResolvedColorToken> dark,
  ) {
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
      ..writeln('// Generated by v3_theme_generator.dart from tokens/**.')
      ..writeln()
      ..writeln("import 'package:flutter/material.dart';")
      ..writeln()
      ..writeln("import 'v3_primitive_colors.g.dart';")
      ..writeln()
      ..writeln('final class V3ColorPalette {')
      ..writeln('  const V3ColorPalette({');
    for (final item in light) {
      buffer.writeln('    required this.${item.token.dartProperty},');
    }
    buffer
      ..writeln('  });')
      ..writeln();
    for (final item in light) {
      buffer.writeln('  final Color ${item.token.dartProperty};');
    }
    buffer
      ..writeln()
      ..writeln('  static const light = V3ColorPalette(');
    _writePaletteValues(buffer, light);
    buffer
      ..writeln('  );')
      ..writeln()
      ..writeln('  static const dark = V3ColorPalette(');
    _writePaletteValues(buffer, dark);
    buffer
      ..writeln('  );')
      ..writeln('}');
    return buffer.toString();
  }

  void _writePaletteValues(
    StringBuffer buffer,
    List<V3ResolvedColorToken> tokens,
  ) {
    for (final item in tokens) {
      buffer.writeln(
        '    ${item.token.dartProperty}: '
        'V3PrimitiveColors.${item.primitive.dartProperty},',
      );
    }
  }

  String _colorLiteral(V3ColorToken token) {
    final hex = token.hex!.substring(1);
    final alpha = (token.alpha * 255).round().clamp(0, 255);
    return '0x${alpha.toRadixString(16).padLeft(2, '0').toUpperCase()}$hex';
  }

  int _writeIfChanged(File file, String content) {
    if (file.existsSync() && file.readAsStringSync() == content) return 0;
    file.writeAsStringSync(content);
    return 1;
  }
}

void main() {
  final scriptDirectory = File.fromUri(Platform.script).parent;
  final repoRoot = scriptDirectory.parent.parent.parent.parent;
  final result = V3ThemeGenerator(repoRoot: repoRoot).generate();
  stdout.writeln(
    'Theme V3 generated: primitives=${result.primitiveCount}, '
    'light=${result.lightCount}, dark=${result.darkCount}, '
    'changedFiles=${result.changedFiles}',
  );
}
